name: 'Artifact Metadata'
description: 'Gather PR / commit metadata, to be used in other actions.'
author: 'govuk-one-login'

inputs:
  github-token:
    description: 'The GitHub token to use for API requests.'
    required: true
  shell:
    description: 'The shell to escape for'
    required: true
    default: 'bash'

outputs:
  json:
    description: 'A JSON object containing metadata about the PR / commit.'
  escaped-json:
    description:
      'A JSON object containing metadata about the PR / commit, with special
      characters escaped.'
  shell:
    description: 'The shell escaped-json was escaped for.'

runs:
  using: node20
  main: dist/index.js
